### PR TITLE
Fix incorrect syntax

### PR DESCRIPTION
**Pull request by Laith98Dev**
I've found it while trying to download it with my plugin `PluginManager`

### CODE REVIEW

**Comment by DuoIncure** [comment]
What's the issue here exactly?

**Comment by Laith98Dev** [comment]
When you do `yaml_parse()` for plugin.yml and tried to get `author` it returned array instead of string!

**Comment by DuoIncure** [comment]
https://github.com/pmmp/PocketMine-MP/blob/stable/src/plugin/PluginDescription.php#L211

PM supports `author` being an array as well as a string. There's no issue on Slapper's behalf. You would have to modify your plugin to account for these cases too.

**Comment by Laith98Dev** [comment]
hmm ok then

**Pull request closed without merging**
